Repository prathimacode-hub/Dev-Mint, pull requests merged in 2025-02, with the labels that each got.

#35 BMI calculator added (Closes #34)
  Chrome Extensions/BMI-Calculator/BMIExtentionWorkingImages/BMINormal.png
  Chrome Extensions/BMI-Calculator/BMIExtentionWorkingImages/BMIOverweight.png
  Chrome Extensions/BMI-Calculator/BMIExtentionWorkingImages/BMIUnderweight.png
  Chrome Extensions/BMI-Calculator/BMIExtentionWorkingImages/BMIextention.png
  Chrome Extensions/BMI-Calculator/Logo-code.png
  Chrome Extensions/BMI-Calculator/manifest.json
  Chrome Extensions/BMI-Calculator/popup.html
  Chrome Extensions/BMI-Calculator/script.js
  Chrome Extensions/BMI-Calculator/style.css
Labels: IWOC2025

#39 Word Meaning App
  HTML+CSS+JS Apps/Word Meaning App/Screenshots/Screen Recording - Made with FlexClip (18).webm
  HTML+CSS+JS Apps/Word Meaning App/Screenshots/WhatsApp Image 2025-02-07 at 20.38.02_51d6cec1.jpg
  HTML+CSS+JS Apps/Word Meaning App/Screenshots/WhatsApp Image 2025-02-07 at 20.39.37_b61db1bc.jpg
  HTML+CSS+JS Apps/Word Meaning App/index.html
  HTML+CSS+JS Apps/Word Meaning App/script.js
Labels: Approved, Hard, IWOC2025

#41 Background-remover-extenion added (Closes #37)
  Chrome Extensions/BackgroundRemover/images/img0.JPG
  Chrome Extensions/BackgroundRemover/images/img1.JPG
  Chrome Extensions/BackgroundRemover/images/img2.JPG
  Chrome Extensions/BackgroundRemover/logo.png
  Chrome Extensions/BackgroundRemover/manifest.json
  Chrome Extensions/BackgroundRemover/popup.html
  Chrome Extensions/BackgroundRemover/script.js
  Chrome Extensions/BackgroundRemover/styles.css
Labels: Approved, Hard, IWOC2025

#42 Snake Game App
  HTML+CSS+JS Apps/Snake Game/Screenshots/Screen Recording - Made with FlexClip (17).webm
  HTML+CSS+JS Apps/Snake Game/Screenshots/WhatsApp Image 2025-02-07 at 20.53.21_e11de4c7.jpg
  HTML+CSS+JS Apps/Snake Game/Screenshots/WhatsApp Image 2025-02-07 at 20.53.28_9d27b17d.jpg
  HTML+CSS+JS Apps/Snake Game/Screenshots/WhatsApp Image 2025-02-07 at 20.53.35_6de050cc.jpg
  HTML+CSS+JS Apps/Snake Game/index.html
  HTML+CSS+JS Apps/Snake Game/script.js
  HTML+CSS+JS Apps/Snake Game/styles.css
Labels: IWOC2025

#43 Added the dice Game App
  HTML+CSS+JS Apps/Dice Game App/Screenshots/Screenshot (75).png
  HTML+CSS+JS Apps/Dice Game App/Screenshots/WhatsApp Image 2025-02-07 at 22.38.34_42314ac0.jpg
  HTML+CSS+JS Apps/Dice Game App/Screenshots/WhatsApp Image 2025-02-07 at 22.39.00_e6242e3f.jpg
  HTML+CSS+JS Apps/Dice Game App/Screenshots/WhatsApp Image 2025-02-07 at 22.39.11_154868a2.jpg
  HTML+CSS+JS Apps/Dice Game App/index.html
  HTML+CSS+JS Apps/Dice Game App/script.js
  HTML+CSS+JS Apps/Dice Game App/styles.css
Labels: Approved, Medium, IWOC2025

#57 Coin Toss Chrome Extension
  Chrome Extensions/Coin Toss Match/Images/check1.png
  Chrome Extensions/Coin Toss Match/Images/check2.png
  Chrome Extensions/Coin Toss Match/Images/heads.png
  Chrome Extensions/Coin Toss Match/Images/tails.png
  Chrome Extensions/Coin Toss Match/app.js
  Chrome Extensions/Coin Toss Match/index.html
  Chrome Extensions/Coin Toss Match/manifest.json
  Chrome Extensions/Coin Toss Match/style.css
Labels: Approved, Hard, IWOC2025

#59 books recommendation extension added (Closes #48)
  Chrome Extensions/Books Recommendation/Images/book.jpg
  Chrome Extensions/Books Recommendation/Images/book3.png
  Chrome Extensions/Books Recommendation/manifest.json
  Chrome Extensions/Books Recommendation/popup.html
  Chrome Extensions/Books Recommendation/script.js
  Chrome Extensions/Books Recommendation/style.css
Labels: Approved, Medium, IWOC2025

#49 CSS Layouts Cheatsheet
  Frontend Layouts/CSS Layouts Cheatsheet/Screenshots/image.png
  Frontend Layouts/CSS Layouts Cheatsheet/index.html
  Frontend Layouts/CSS Layouts Cheatsheet/styles.css
Labels: Approved, Medium, IWOC2025

#60 Code Aider Extension Added Closes #50
  Chrome Extensions/Code Aider/Images/check.png
  Chrome Extensions/Code Aider/Images/icon128.png
  Chrome Extensions/Code Aider/Images/icon150.png
  Chrome Extensions/Code Aider/Images/icon19.png
  Chrome Extensions/Code Aider/manifest.json
  Chrome Extensions/Code Aider/popup.css
  Chrome Extensions/Code Aider/popup.html
Labels: Approved, Medium, IWOC2025

#65 Rock Paper & Scissor Game
  HTML+CSS+JS Apps/Rock Paper Scissor Game/Screenshots/Screen Recording - Made with FlexClip (21).webm
  HTML+CSS+JS Apps/Rock Paper Scissor Game/Screenshots/WhatsApp Image 2025-02-08 at 21.50.26_920753a9.jpg
  HTML+CSS+JS Apps/Rock Paper Scissor Game/Screenshots/WhatsApp Image 2025-02-08 at 21.50.35_ed24c023.jpg
  HTML+CSS+JS Apps/Rock Paper Scissor Game/index.html
  HTML+CSS+JS Apps/Rock Paper Scissor Game/script.js
  HTML+CSS+JS Apps/Rock Paper Scissor Game/style.css
Labels: Approved, Hard, IWOC2025

#66 Space Shooter Game
  HTML+CSS+JS Apps/Space Shooter Game/Screenshots/Screen Recording - Made with FlexClip (22).webm
  HTML+CSS+JS Apps/Space Shooter Game/Screenshots/WhatsApp Image 2025-02-08 at 22.33.02_68a14686.jpg
  HTML+CSS+JS Apps/Space Shooter Game/index.html
  HTML+CSS+JS Apps/Space Shooter Game/script.js
  HTML+CSS+JS Apps/Space Shooter Game/style.css
Labels: Approved, Hard, IWOC2025

#67 Rubik Cube Added Closes#51
  Chrome Extensions/Rubik Cube/Images/logo.png
  Chrome Extensions/Rubik Cube/index.html
  Chrome Extensions/Rubik Cube/manifest.json
  Chrome Extensions/Rubik Cube/script.js
  Chrome Extensions/Rubik Cube/script1.js
  Chrome Extensions/Rubik Cube/style.css
Labels: Approved, Hard, IWOC2025

#63 Dinosaur Hurdle Game App
  HTML+CSS+JS Apps/Dinosaur Hurdle Game App/Screenshots/image.png
  HTML+CSS+JS Apps/Dinosaur Hurdle Game App/index.html
  HTML+CSS+JS Apps/Dinosaur Hurdle Game App/script.js
Labels: Approved, Hard, IWOC2025

#68 Unified Access to All Tools & Games WebApp
  assets/BMI_Calcu.png
  assets/background_remover.jpg
  assets/backwall.jpg
  assets/bg.jpg
  assets/comsoon.jpg
  assets/dicbg.jpg
  assets/numberguess.jpg
  assets/snakegamebg.jpg
  index.html
  style.css
Labels: Approved, Medium, IWOC2025

#72 Ping Pong Game App
  HTML+CSS+JS Apps/Ping Pong Game/Screenshots/image.png
  HTML+CSS+JS Apps/Ping Pong Game/index.html
  HTML+CSS+JS Apps/Ping Pong Game/script.js
  HTML+CSS+JS Apps/Ping Pong Game/style.css
Labels: Approved, Medium, IWOC2025

#74 Countdown Timer Extension Added (Closes #52)
  Chrome Extensions/Countdown Timer/Screenshots/Recording 2025-02-09 113302.mp4
  Chrome Extensions/Countdown Timer/background.js
  Chrome Extensions/Countdown Timer/manifest.json
  Chrome Extensions/Countdown Timer/popup.html
  Chrome Extensions/Countdown Timer/popup.js
  Chrome Extensions/Countdown Timer/style.css
Labels: Approved, Easy, IWOC2025

#55 Simon Game App
  HTML+CSS+JS Apps/Simon Game/index.html
  HTML+CSS+JS Apps/Simon Game/index.js
  HTML+CSS+JS Apps/Simon Game/sounds/sounds/blue.mp3
  HTML+CSS+JS Apps/Simon Game/sounds/sounds/green.mp3
  HTML+CSS+JS Apps/Simon Game/sounds/sounds/red.mp3
  HTML+CSS+JS Apps/Simon Game/sounds/sounds/wrong.mp3
  HTML+CSS+JS Apps/Simon Game/sounds/sounds/yellow.mp3
  HTML+CSS+JS Apps/Simon Game/styles.css
Labels: Approved, Easy, IWOC2025

#83 Age Calculator Chrome Extension
  Chrome Extensions/Age Calculator/Images/check1.png
  Chrome Extensions/Age Calculator/Images/check2.png
  Chrome Extensions/Age Calculator/Images/logo.png
  Chrome Extensions/Age Calculator/index.html
  Chrome Extensions/Age Calculator/manifest.json
  Chrome Extensions/Age Calculator/script.js
  Chrome Extensions/Age Calculator/style.css
Labels: Approved, Easy, IWOC2025

#87 2048 Puzzle Game App Added
  HTML+CSS+JS Apps/2048 Puzzle Game App/Screenshots/Screen Recording - Made with FlexClip (24).webm
  HTML+CSS+JS Apps/2048 Puzzle Game App/Screenshots/WhatsApp Image 2025-02-11 at 11.24.33_a2c1882a.jpg
  HTML+CSS+JS Apps/2048 Puzzle Game App/Screenshots/WhatsApp Image 2025-02-11 at 11.24.40_b03a0108.jpg
  HTML+CSS+JS Apps/2048 Puzzle Game App/Screenshots/WhatsApp Image 2025-02-11 at 11.24.52_5c6fbdf6.jpg
  HTML+CSS+JS Apps/2048 Puzzle Game App/Screenshots/WhatsApp Image 2025-02-11 at 11.25.04_3d2d6666.jpg
  HTML+CSS+JS Apps/2048 Puzzle Game App/index.html
  HTML+CSS+JS Apps/2048 Puzzle Game App/script.js
  HTML+CSS+JS Apps/2048 Puzzle Game App/style.css
Labels: Approved, Medium, IWOC2025

#84 Calculator Chrome Extension
  Chrome Extensions/Calculator/Images/calculatorimg.png
  Chrome Extensions/Calculator/Images/icons128.png
  Chrome Extensions/Calculator/Images/icons16.png
  Chrome Extensions/Calculator/Images/icons48.png
  Chrome Extensions/Calculator/manifest.json
  Chrome Extensions/Calculator/popup.html
  Chrome Extensions/Calculator/popup.js
  Chrome Extensions/Calculator/style.css
Labels: Approved, Easy, IWOC2025

#90 Rhythm Based Game App
  HTML+CSS+JS Apps/Rhythm Based Game App/Screenshots/Screen Recording - Made with FlexClip (25).webm
  HTML+CSS+JS Apps/Rhythm Based Game App/Screenshots/WhatsApp Image 2025-02-13 at 14.37.07_ada87bff.jpg
  HTML+CSS+JS Apps/Rhythm Based Game App/Screenshots/WhatsApp Image 2025-02-13 at 14.37.19_73e67745.jpg
  HTML+CSS+JS Apps/Rhythm Based Game App/index.html
  HTML+CSS+JS Apps/Rhythm Based Game App/script.js
  HTML+CSS+JS Apps/Rhythm Based Game App/style.css
Labels: Approved, Medium, IWOC2025

#89 Analog Clock App
  HTML+CSS+JS Apps/Analog Clock/Screenshots/Screenshot 2025-02-12 092652.png
  HTML+CSS+JS Apps/Analog Clock/Screenshots/Screenshot 2025-02-12 092708.png
  HTML+CSS+JS Apps/Analog Clock/index.html
  HTML+CSS+JS Apps/Analog Clock/script.js
  HTML+CSS+JS Apps/Analog Clock/style.css
Labels: Approved, Easy, IWOC2025

#92 Calendar App added
  HTML+CSS+JS Apps/Calendar App/Screenshots/Screenshot 2025-02-16 001601.png
  HTML+CSS+JS Apps/Calendar App/Screenshots/Screenshot 2025-02-16 001657.png
  HTML+CSS+JS Apps/Calendar App/index.html
  HTML+CSS+JS Apps/Calendar App/script.js
  HTML+CSS+JS Apps/Calendar App/style.css
Labels: Approved, Easy, IWOC2025

#113 Blacklist Website Chrome Extension
  Chrome Extensions/Blacklist Website/Images/blacklist.PNG
  Chrome Extensions/Blacklist Website/Images/icon-128x128.png
  Chrome Extensions/Blacklist Website/Images/icon-16x16.png
  Chrome Extensions/Blacklist Website/Images/icon-48x48-off.png
  Chrome Extensions/Blacklist Website/Images/icon-48x48.png
  Chrome Extensions/Blacklist Website/background.js
  Chrome Extensions/Blacklist Website/manifest.json
  Chrome Extensions/Blacklist Website/popup.css
  Chrome Extensions/Blacklist Website/popup.html
  Chrome Extensions/Blacklist Website/popup.js
Labels: Approved, Hard, IWOC2025

#124 Body Surface Area Calculator
  Calculators/Body Surface Area Calculator/Screenshots/Screen Recording - Made with FlexClip (34).webm
  Calculators/Body Surface Area Calculator/Screenshots/WhatsApp Image 2025-02-19 at 00.23.25_9314c7f5.jpg
  Calculators/Body Surface Area Calculator/Screenshots/WhatsApp Image 2025-02-19 at 00.23.31_a821af41.jpg
  Calculators/Body Surface Area Calculator/index.html
  Calculators/Body Surface Area Calculator/script.js
  Calculators/Body Surface Area Calculator/style.css
Labels: Approved, Medium, IWOC2025

#125 Add Logo,favicon,Enhancing Footer
  assets/logo.png
  index.html
  style.css
Labels: Approved, Easy, IWOC2025

#126 Add Age Calculator
  Calculators/Age Calculator/age.png
  Calculators/Age Calculator/index.html
  Calculators/Age Calculator/script.js
  Calculators/Age Calculator/style.css
  index.html
Labels: Approved, Easy, IWOC2025

#129 Air Quality Index Calculator
  Calculators/Air Quality Index Calculator/Screenshots/Screen Recording - Made with FlexClip (37).webm
  Calculators/Air Quality Index Calculator/Screenshots/WhatsApp Image 2025-02-20 at 21.04.27_b843c1ee.jpg
  Calculators/Air Quality Index Calculator/Screenshots/WhatsApp Image 2025-02-20 at 21.04.34_de7a3ded.jpg
  Calculators/Air Quality Index Calculator/index.html
  Calculators/Air Quality Index Calculator/script.js
  Calculators/Air Quality Index Calculator/style.css
Labels: Approved, Medium, IWOC2025

#130 Anagram Calculator
  Calculators/Anagram Calculator/Screenshots/Screen Recording - Made with FlexClip (37).webm
  Calculators/Anagram Calculator/Screenshots/WhatsApp Image 2025-02-20 at 21.18.03_26ec9bb0.jpg
  Calculators/Anagram Calculator/Screenshots/WhatsApp Image 2025-02-20 at 21.18.12_e26a5679.jpg
  Calculators/Anagram Calculator/index.html
  Calculators/Anagram Calculator/script.js
  Calculators/Anagram Calculator/style.css
Labels: Approved, Easy, IWOC2025

#144 GitSpot User
  HTML+CSS+JS Apps/Gitspot User/Screenshots/Gitspot User.mp4
  HTML+CSS+JS Apps/Gitspot User/Screenshots/image1.png
  HTML+CSS+JS Apps/Gitspot User/Screenshots/image2.png
  HTML+CSS+JS Apps/Gitspot User/index.html
  HTML+CSS+JS Apps/Gitspot User/script.js
  HTML+CSS+JS Apps/Gitspot User/style.css
Labels: Approved, Easy, IWOC2025

#146 Cooking Website Frontend Layout
  Frontend Layouts/Cooking Website Frontend Layout/about_us.html
  Frontend Layouts/Cooking Website Frontend Layout/carbonara.html
  Frontend Layouts/Cooking Website Frontend Layout/chicken-curry.html
  Frontend Layouts/Cooking Website Frontend Layout/contact.html
  Frontend Layouts/Cooking Website Frontend Layout/contact_about.css
  Frontend Layouts/Cooking Website Frontend Layout/images/banner1.jpg
  Frontend Layouts/Cooking Website Frontend Layout/images/banner2.jpg
  Frontend Layouts/Cooking Website Frontend Layout/images/banner3.jpg
  Frontend Layouts/Cooking Website Frontend Layout/images/blank-profile-picture.webp
  Frontend Layouts/Cooking Website Frontend Layout/images/carbonara.jpg
  Frontend Layouts/Cooking Website Frontend Layout/images/chicken-curry.jpg
  Frontend Layouts/Cooking Website Frontend Layout/images/vegan-salad.jpg
  Frontend Layouts/Cooking Website Frontend Layout/index.html
  Frontend Layouts/Cooking Website Frontend Layout/recipe_detail.css
  Frontend Layouts/Cooking Website Frontend Layout/recipes.css
  Frontend Layouts/Cooking Website Frontend Layout/recipes.html
  Frontend Layouts/Cooking Website Frontend Layout/styles.css
  Frontend Layouts/Cooking Website Frontend Layout/user_dash.css
  Frontend Layouts/Cooking Website Frontend Layout/user_dash.html
  Frontend Layouts/Cooking Website Frontend Layout/vegan-salad.html
Labels: Approved, Medium, IWOC2025

#161 Website - Homepage Overall Enhancement with 7 Features
  copyrightYear.js
  index.html
  main.html
  scrollTop.js
  style.css
Labels: Approved, Easy, IWOC2025

#162 Factorial Calculator
  Calculators/Factorial Calculator/Screenshots/Factorial Calculator.mp4
  Calculators/Factorial Calculator/Screenshots/image.png
  Calculators/Factorial Calculator/index.html
  Calculators/Factorial Calculator/script.js
  Calculators/Factorial Calculator/style.css
Labels: Approved, Easy, IWOC2025

#199 Binary Calculator
  Calculators/Binary Calculator/Screenshots/Binary Calculator.mp4
  Calculators/Binary Calculator/Screenshots/image1.png
  Calculators/Binary Calculator/Screenshots/image2.png
  Calculators/Binary Calculator/background.png
  Calculators/Binary Calculator/index.html
  Calculators/Binary Calculator/script.js
  Calculators/Binary Calculator/style.css
Labels: Approved, Easy, IWOC2025

#198 404 Custom Error Page
  404.html
  assets/404.png
Labels: Approved, Easy, IWOC2025
